/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto;

import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import projeto.ValidaCPF;

/**
 *
 * @author user
 */
public class MenuMotoristaAlterar extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuMotoristaAlterar(String CPF) {
        initComponents();
        String ID = "",Nome,DataNasc,Cidade,Endereco,TipoCarteira,NumeroCelular,Ativo;
        if (CPF != null){
            jFormattedTextFieldCPF.setText(CPF);
            try {
            ID = AlterarMotorista.ValidaID(CPF);
        } catch (ClassNotFoundException ex) {}
        if(!"B".equals(ID)){
            if(!"false".equals(ID)){                
                    
                    jFormattedTextFieldCPF.setEditable(false);
                    jFormattedTextFieldCPF.setBackground(new java.awt.Color(204,204,204));
                    jFormattedTextFieldCPF.setFocusable(false);
                    
                    jTextFieldNome.setEditable(true);
                    jTextFieldNome.setBackground(new java.awt.Color(255, 255, 255));
                    jTextFieldNome.setFocusable(true);

                    jFormattedTextFieldDataNasc.setEditable(true);
                    jFormattedTextFieldDataNasc.setBackground(new java.awt.Color(255, 255, 255));
                    jFormattedTextFieldDataNasc.setFocusable(true);

                    jTextFieldCidade.setEditable(true);
                    jTextFieldCidade.setBackground(new java.awt.Color(255, 255, 255));
                    jTextFieldCidade.setFocusable(true);

                    jTextFieldEndereco.setEditable(true);
                    jTextFieldEndereco.setBackground(new java.awt.Color(255, 255, 255));
                    jTextFieldEndereco.setFocusable(true);

                    jTextFieldTipoCarteira.setEditable(true);
                    jTextFieldTipoCarteira.setBackground(new java.awt.Color(255, 255, 255));
                    jTextFieldTipoCarteira.setFocusable(true);
                    
                    jFormattedTextFieldNumero.setEditable(true);
                    jFormattedTextFieldNumero.setBackground(new java.awt.Color(255, 255, 255));
                    jFormattedTextFieldNumero.setFocusable(true);
                    
                    jButtonAltMotorista.setEnabled(true);                   
                    jCheckBoxAtivo.setEnabled(true);
                    
                try {
                    Nome = AlterarMotorista.GetNome(ID);
                    DataNasc = AlterarMotorista.GetDataNasc(ID);
                    Cidade = AlterarMotorista.GetCidade(ID);
                    Endereco = AlterarMotorista.GetEndereco(ID);
                    TipoCarteira = AlterarMotorista.GetTipoCarteira(ID);
                    NumeroCelular = AlterarMotorista.GetNumeroCelular(ID);
                    Ativo = AlterarMotorista.GetAtivo(ID);
                    
                    jTextFieldNome.setText(Nome);
                    jFormattedTextFieldDataNasc.setText(DataNasc);
                    jTextFieldCidade.setText(Cidade);
                    jTextFieldEndereco.setText(Endereco);
                    jTextFieldTipoCarteira.setText(TipoCarteira);
                    jFormattedTextFieldNumero.setText(NumeroCelular);
                    
                    if (Ativo.equals("Y")){
                        jCheckBoxAtivo.setSelected(true);
                    }
                    if (Ativo.equals("N")){
                        jCheckBoxAtivo.setSelected(false);
                    }
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(MenuMotoristaAlterar.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                
                    
                    

            }else{
                final JPanel panel = new JPanel();
                JOptionPane.showMessageDialog(panel, "CPF não localizado, favor revisar", "ERRO!",
                JOptionPane.WARNING_MESSAGE);
            }
        }else{
            final JPanel panel = new JPanel();
            JOptionPane.showMessageDialog(panel, "Preencher campo de CPF", "ERRO!",
            JOptionPane.WARNING_MESSAGE);
        }
            
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelLogo = new javax.swing.JLabel();
        jButtonVoltar = new javax.swing.JButton();
        jLabelTitulo = new javax.swing.JLabel();
        jButtonAltMotorista = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabelNome = new javax.swing.JLabel();
        jLabelDataNasc = new javax.swing.JLabel();
        jLabelCPF = new javax.swing.JLabel();
        jLabelCidade = new javax.swing.JLabel();
        jLabelEndereco = new javax.swing.JLabel();
        jLabelCarteira = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jTextFieldCidade = new javax.swing.JTextField();
        jTextFieldEndereco = new javax.swing.JTextField();
        jTextFieldTipoCarteira = new javax.swing.JTextField();
        jFormattedTextFieldCPF = new javax.swing.JFormattedTextField();
        jFormattedTextFieldDataNasc = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jFormattedTextFieldNumero = new javax.swing.JFormattedTextField();
        jButtonBuscar = new javax.swing.JButton();
        jCheckBoxAtivo = new javax.swing.JCheckBox();
        jButtonNovaBusca = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Gestão de Rotas");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/74ec9ee6-a826-4d38-ba41-d7db8d8fed22_200x200.png"))); // NOI18N

        jButtonVoltar.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButtonVoltar.setText("Voltar");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });

        jLabelTitulo.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabelTitulo.setText("Alterar Cadastro de Motoristas");

        jButtonAltMotorista.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButtonAltMotorista.setText("Alterar Motorista");
        jButtonAltMotorista.setEnabled(false);
        jButtonAltMotorista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAltMotoristaActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelNome.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabelNome.setText("Nome:");

        jLabelDataNasc.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabelDataNasc.setText("Data Nascimento:");

        jLabelCPF.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabelCPF.setText("CPF:");

        jLabelCidade.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabelCidade.setText("Cidade:");

        jLabelEndereco.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabelEndereco.setText("Endereço:");

        jLabelCarteira.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabelCarteira.setText("Tipo Carteira:");

        jTextFieldNome.setEditable(false);
        jTextFieldNome.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldNome.setFocusable(false);

        jTextFieldCidade.setEditable(false);
        jTextFieldCidade.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldCidade.setFocusable(false);

        jTextFieldEndereco.setEditable(false);
        jTextFieldEndereco.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldEndereco.setFocusable(false);

        jTextFieldTipoCarteira.setEditable(false);
        jTextFieldTipoCarteira.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldTipoCarteira.setFocusable(false);

        try {
            jFormattedTextFieldCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldCPFActionPerformed(evt);
            }
        });

        jFormattedTextFieldDataNasc.setEditable(false);
        jFormattedTextFieldDataNasc.setBackground(new java.awt.Color(204, 204, 204));
        jFormattedTextFieldDataNasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy/MM/dd"))));
        jFormattedTextFieldDataNasc.setToolTipText("AAAA/MM/DD");
        jFormattedTextFieldDataNasc.setFocusable(false);

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel1.setText("Numero Celular:");

        jFormattedTextFieldNumero.setEditable(false);
        jFormattedTextFieldNumero.setBackground(new java.awt.Color(204, 204, 204));
        try {
            jFormattedTextFieldNumero.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldNumero.setToolTipText("(DD)9xxxx-xxxx");
        jFormattedTextFieldNumero.setFocusable(false);

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.setToolTipText("");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jCheckBoxAtivo.setText("Ativo");
        jCheckBoxAtivo.setEnabled(false);

        jButtonNovaBusca.setText("Nova Busca");
        jButtonNovaBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovaBuscaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelDataNasc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextFieldDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextFieldNumero))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelCarteira)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldTipoCarteira))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelEndereco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldEndereco))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelCidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldCidade))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelCPF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jFormattedTextFieldCPF))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonBuscar)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jCheckBoxAtivo)
                                .addGap(36, 36, 36))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                        .addComponent(jButtonNovaBusca)
                        .addGap(18, 18, 18))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNome)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxAtivo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDataNasc)
                    .addComponent(jFormattedTextFieldDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCPF)
                    .addComponent(jFormattedTextFieldCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscar))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCidade)
                    .addComponent(jTextFieldCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEndereco)
                    .addComponent(jTextFieldEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCarteira)
                    .addComponent(jTextFieldTipoCarteira, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jFormattedTextFieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNovaBusca))
                .addGap(61, 61, 61))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(290, 290, 290)
                .addComponent(jLabelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(276, 276, 276)
                .addComponent(jLabelTitulo))
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonAltMotorista)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAltMotorista)
                    .addComponent(jButtonVoltar))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
                     MenuMotorista motorista = new MenuMotorista();
                    motorista.setVisible(true);
                    dispose();                       
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jFormattedTextFieldCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldCPFActionPerformed

    private void jButtonAltMotoristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAltMotoristaActionPerformed
        String nome,datanasc,cidade,endereco,tipocarteira,telefone,cpf,ativo;
        if(jFormattedTextFieldCPF.getText().equals("   .   .   -  ")){
            cpf=null;
        }else cpf = jFormattedTextFieldCPF.getText();
        if(jTextFieldNome.getText().equals("")){
            nome = null;
        }else nome = jTextFieldNome.getText();
        if(jFormattedTextFieldDataNasc.getText().equals("")){
            datanasc = null;
        }else datanasc = jFormattedTextFieldDataNasc.getText();
        if(jTextFieldCidade.getText().equals("")){
            cidade = null;
        }else cidade = jTextFieldCidade.getText();
        if(jTextFieldEndereco.getText().equals("")){
            endereco = null;
        }else endereco = jTextFieldEndereco.getText();
        if(jTextFieldTipoCarteira.getText().equals("")){
            tipocarteira = null;
        }else tipocarteira = jTextFieldTipoCarteira.getText();
        if(jFormattedTextFieldNumero.getText().equals("")){
            telefone = null;
        }else telefone = jFormattedTextFieldNumero.getText();
        if (jCheckBoxAtivo.isSelected()){
            ativo ="Y";
            } else ativo ="N";
        
        try {
            AlterarMotorista.AtualizaMotorista(nome, cpf, datanasc, cidade, endereco, tipocarteira, telefone, ativo);
            
        } catch (ParseException ex) {
            Logger.getLogger(MenuMotoristaAlterar.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MenuMotoristaAlterar.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jButtonAltMotoristaActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
       String ID = "",CPF,Nome,DataNasc,Cidade,Endereco,TipoCarteira,NumeroCelular,Ativo;
        if(jFormattedTextFieldCPF.getText().equals("   .   .   -  ")){
            CPF=null;
        }else CPF = jFormattedTextFieldCPF.getText();
        try {
            ID = AlterarMotorista.ValidaID(CPF);
        } catch (ClassNotFoundException ex) {}
        if(!"B".equals(ID)){
            if(!"false".equals(ID)){                
                    
                    jFormattedTextFieldCPF.setEditable(false);
                    jFormattedTextFieldCPF.setBackground(new java.awt.Color(204,204,204));
                    jFormattedTextFieldCPF.setFocusable(false);
                    
                    jTextFieldNome.setEditable(true);
                    jTextFieldNome.setBackground(new java.awt.Color(255, 255, 255));
                    jTextFieldNome.setFocusable(true);

                    jFormattedTextFieldDataNasc.setEditable(true);
                    jFormattedTextFieldDataNasc.setBackground(new java.awt.Color(255, 255, 255));
                    jFormattedTextFieldDataNasc.setFocusable(true);

                    jTextFieldCidade.setEditable(true);
                    jTextFieldCidade.setBackground(new java.awt.Color(255, 255, 255));
                    jTextFieldCidade.setFocusable(true);

                    jTextFieldEndereco.setEditable(true);
                    jTextFieldEndereco.setBackground(new java.awt.Color(255, 255, 255));
                    jTextFieldEndereco.setFocusable(true);

                    jTextFieldTipoCarteira.setEditable(true);
                    jTextFieldTipoCarteira.setBackground(new java.awt.Color(255, 255, 255));
                    jTextFieldTipoCarteira.setFocusable(true);
                    
                    jFormattedTextFieldNumero.setEditable(true);
                    jFormattedTextFieldNumero.setBackground(new java.awt.Color(255, 255, 255));
                    jFormattedTextFieldNumero.setFocusable(true);
                    
                    jButtonAltMotorista.setEnabled(true);                   
                    jCheckBoxAtivo.setEnabled(true);
                    
                try {
                    Nome = AlterarMotorista.GetNome(ID);
                    DataNasc = AlterarMotorista.GetDataNasc(ID);
                    Cidade = AlterarMotorista.GetCidade(ID);
                    Endereco = AlterarMotorista.GetEndereco(ID);
                    TipoCarteira = AlterarMotorista.GetTipoCarteira(ID);
                    NumeroCelular = AlterarMotorista.GetNumeroCelular(ID);
                    Ativo = AlterarMotorista.GetAtivo(ID);
                    
                    jTextFieldNome.setText(Nome);
                    jFormattedTextFieldDataNasc.setText(DataNasc);
                    jTextFieldCidade.setText(Cidade);
                    jTextFieldEndereco.setText(Endereco);
                    jTextFieldTipoCarteira.setText(TipoCarteira);
                    jFormattedTextFieldNumero.setText(NumeroCelular);
                    
                    if (Ativo.equals("Y")){
                        jCheckBoxAtivo.setSelected(true);
                    }
                    if (Ativo.equals("N")){
                        jCheckBoxAtivo.setSelected(false);
                    }
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(MenuMotoristaAlterar.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                
                    
                    

            }else{
                final JPanel panel = new JPanel();
                JOptionPane.showMessageDialog(panel, "CPF não localizado, favor revisar", "ERRO!",
                JOptionPane.WARNING_MESSAGE);
            }
        }else{
            final JPanel panel = new JPanel();
            JOptionPane.showMessageDialog(panel, "Preencher campo de CPF", "ERRO!",
            JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonNovaBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovaBuscaActionPerformed
                    String A = null;
                    MenuMotoristaAlterar.AltMotorista(A);                    
                    dispose();
    }//GEN-LAST:event_jButtonNovaBuscaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void AltMotorista(String CPF) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuMotoristaAlterar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuMotoristaAlterar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuMotoristaAlterar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuMotoristaAlterar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {                
                new MenuMotoristaAlterar(CPF).setVisible(true);
            }
        });
    }
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAltMotorista;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonNovaBusca;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JCheckBox jCheckBoxAtivo;
    private javax.swing.JFormattedTextField jFormattedTextFieldCPF;
    private javax.swing.JFormattedTextField jFormattedTextFieldDataNasc;
    private javax.swing.JFormattedTextField jFormattedTextFieldNumero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCPF;
    private javax.swing.JLabel jLabelCarteira;
    private javax.swing.JLabel jLabelCidade;
    private javax.swing.JLabel jLabelDataNasc;
    private javax.swing.JLabel jLabelEndereco;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldCidade;
    private javax.swing.JTextField jTextFieldEndereco;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldTipoCarteira;
    // End of variables declaration//GEN-END:variables
}
