/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class MenuTransportes extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuTransportes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButtonTransportesAndamento = new javax.swing.JButton();
        jButtonTransportesRealizados = new javax.swing.JButton();
        jButtonTransportesFuturos = new javax.swing.JButton();
        jButtonBuscarTransporte = new javax.swing.JButton();
        jButtonVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Gestão de Rotas");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/74ec9ee6-a826-4d38-ba41-d7db8d8fed22_200x200.png"))); // NOI18N

        jButtonTransportesAndamento.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jButtonTransportesAndamento.setText("Transportes em Andamento");
        jButtonTransportesAndamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTransportesAndamentoActionPerformed(evt);
            }
        });

        jButtonTransportesRealizados.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jButtonTransportesRealizados.setText("Transportes Realizados");
        jButtonTransportesRealizados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTransportesRealizadosActionPerformed(evt);
            }
        });

        jButtonTransportesFuturos.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jButtonTransportesFuturos.setText("Transportes Futuros");
        jButtonTransportesFuturos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTransportesFuturosActionPerformed(evt);
            }
        });

        jButtonBuscarTransporte.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jButtonBuscarTransporte.setText("Buscar Transporte");
        jButtonBuscarTransporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarTransporteActionPerformed(evt);
            }
        });

        jButtonVoltar.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButtonVoltar.setText("Voltar");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonTransportesRealizados, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonTransportesFuturos)
                    .addComponent(jButtonBuscarTransporte)
                    .addComponent(jButtonTransportesAndamento))
                .addContainerGap(483, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 290, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonTransportesAndamento, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jButtonTransportesRealizados)
                .addGap(32, 32, 32)
                .addComponent(jButtonTransportesFuturos)
                .addGap(34, 34, 34)
                .addComponent(jButtonBuscarTransporte)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jButtonVoltar)
                .addGap(20, 20, 20))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonTransportesAndamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTransportesAndamentoActionPerformed
        MenuTransportesAndamento andamento = null;
        try {
            andamento = new MenuTransportesAndamento();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MenuTransportes.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MenuTransportes.class.getName()).log(Level.SEVERE, null, ex);
        }
                    andamento.setVisible(true);
                    dispose();
    }//GEN-LAST:event_jButtonTransportesAndamentoActionPerformed

    private void jButtonTransportesRealizadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTransportesRealizadosActionPerformed
        MenuTransportesRealizados realizados = null;
        try {
            realizados = new MenuTransportesRealizados();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MenuTransportes.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MenuTransportes.class.getName()).log(Level.SEVERE, null, ex);
        }
                    realizados.setVisible(true);
                    dispose();
    }//GEN-LAST:event_jButtonTransportesRealizadosActionPerformed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
                    MenuPrincipal menu = new MenuPrincipal();
                    menu.setVisible(true);
                    dispose();                
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jButtonBuscarTransporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarTransporteActionPerformed
                    MenuBuscar buscar = new MenuBuscar();
                    buscar.setVisible(true);
                    dispose();    
    }//GEN-LAST:event_jButtonBuscarTransporteActionPerformed

    private void jButtonTransportesFuturosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTransportesFuturosActionPerformed
                    MenuTransportesFuturos futuro = null;
        try {
            futuro = new MenuTransportesFuturos();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MenuTransportes.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MenuTransportes.class.getName()).log(Level.SEVERE, null, ex);
        }
                    futuro.setVisible(true);
                    dispose();   
    }//GEN-LAST:event_jButtonTransportesFuturosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuTransportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuTransportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuTransportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuTransportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuTransportes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscarTransporte;
    private javax.swing.JButton jButtonTransportesAndamento;
    private javax.swing.JButton jButtonTransportesFuturos;
    private javax.swing.JButton jButtonTransportesRealizados;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
