/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author user
 */
public class MenuVeiculoAlterar extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuVeiculoAlterar(String Placa) {
        initComponents();
        String ID="", Fabricante, Modelo, Motorista, Peso, Cubagem, Ativo;
        if(Placa != null){
            jTextFieldPlaca.setText(Placa);
            try {
            ID = AlterarVeiculo.ValidaPlaca(Placa);
        } catch (ClassNotFoundException ex) {}
        if(!"B".equals(ID)){
            if(!"N".equals(ID)){
                if(!"false".equals(ID)){

                    jTextFieldFabricante.setEditable(true);
                    jTextFieldFabricante.setBackground(new java.awt.Color(255, 255, 255));
                    jTextFieldFabricante.setFocusable(true);

                    jTextFieldModelo.setEditable(true);
                    jTextFieldModelo.setBackground(new java.awt.Color(255, 255, 255));
                    jTextFieldModelo.setFocusable(true);

                    jTextFieldMotorista.setEditable(true);
                    jTextFieldMotorista.setBackground(new java.awt.Color(255, 255, 255));
                    jTextFieldMotorista.setFocusable(true);

                    jTextFieldPeso.setEditable(true);
                    jTextFieldPeso.setBackground(new java.awt.Color(255, 255, 255));
                    jTextFieldPeso.setFocusable(true);

                    jTextFieldCubagem.setEditable(true);
                    jTextFieldCubagem.setBackground(new java.awt.Color(255, 255, 255));
                    jTextFieldCubagem.setFocusable(true);

                    jTextFieldPlaca.setEditable(false);
                    jTextFieldPlaca.setBackground(new java.awt.Color(204, 204, 204));
                    jTextFieldPlaca.setFocusable(false);

                    jButtonAltVeiculo.setEnabled(true); 
                    jCheckBoxAtivo.setEnabled(true);
                    
                    try {
                        Fabricante = AlterarVeiculo.GetFabricante(ID);
                        Modelo = AlterarVeiculo.GetModelo(ID);
                        Motorista = AlterarVeiculo.GetMotorista(ID);
                        Peso = AlterarVeiculo.GetPeso(ID);
                        Cubagem = AlterarVeiculo.GetCubagem(ID);
                        Ativo = AlterarVeiculo.GetAtivo(ID);
                        
                        jTextFieldFabricante.setText(Fabricante);
                        jTextFieldModelo.setText(Modelo);
                        jTextFieldMotorista.setText(Motorista);
                        jTextFieldPeso.setText(Peso);
                        jTextFieldCubagem.setText(Cubagem);
                        
                        
                        if (Ativo.equals("Y")){
                        jCheckBoxAtivo.setSelected(true);
                        }
                        if (Ativo.equals("N")){
                        jCheckBoxAtivo.setSelected(false);
                        }
                        } catch (ClassNotFoundException ex) {
                            Logger.getLogger(MenuVeiculoAlterar.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    

                }else{
                    final JPanel panel = new JPanel();
                    JOptionPane.showMessageDialog(panel, "Placa não localizada, favor revisar", "ERRO!",
                    JOptionPane.WARNING_MESSAGE);
                }
            }else{
                final JPanel panel = new JPanel();
                JOptionPane.showMessageDialog(panel, "Placa Incorreta, favor revisar", "ERRO!",
                JOptionPane.WARNING_MESSAGE);
            }
        }else{
            final JPanel panel = new JPanel();
            JOptionPane.showMessageDialog(panel, "Preencher campo de Placa", "ERRO!",
            JOptionPane.WARNING_MESSAGE);
        }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelLogo = new javax.swing.JLabel();
        jButtonVoltar = new javax.swing.JButton();
        jLabelTitulo = new javax.swing.JLabel();
        jButtonAltVeiculo = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabelPlaca = new javax.swing.JLabel();
        jLabelFabricante = new javax.swing.JLabel();
        jLabelModelo = new javax.swing.JLabel();
        jLabelMotorista = new javax.swing.JLabel();
        jLabelPeso = new javax.swing.JLabel();
        jLabelCubagem = new javax.swing.JLabel();
        jTextFieldPlaca = new javax.swing.JTextField();
        jTextFieldFabricante = new javax.swing.JTextField();
        jTextFieldModelo = new javax.swing.JTextField();
        jTextFieldMotorista = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldPeso = new javax.swing.JFormattedTextField();
        jTextFieldCubagem = new javax.swing.JFormattedTextField();
        jButtonBuscar = new javax.swing.JButton();
        jCheckBoxAtivo = new javax.swing.JCheckBox();
        jButtonNovaBusca = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Gestão de Rotas");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/74ec9ee6-a826-4d38-ba41-d7db8d8fed22_200x200.png"))); // NOI18N

        jButtonVoltar.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButtonVoltar.setText("Voltar");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });

        jLabelTitulo.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabelTitulo.setText("Alterar Cadastro de Veiculo");

        jButtonAltVeiculo.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButtonAltVeiculo.setText("Alterar Cadastro");
        jButtonAltVeiculo.setEnabled(false);
        jButtonAltVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAltVeiculoActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelPlaca.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabelPlaca.setText("Placa:");

        jLabelFabricante.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabelFabricante.setText("Fabricante:");

        jLabelModelo.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabelModelo.setText("Modelo:");

        jLabelMotorista.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabelMotorista.setText("Motorista:");

        jLabelPeso.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabelPeso.setText("Peso:");

        jLabelCubagem.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabelCubagem.setText("Cubagem:");

        jTextFieldFabricante.setEditable(false);
        jTextFieldFabricante.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldFabricante.setFocusable(false);

        jTextFieldModelo.setEditable(false);
        jTextFieldModelo.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldModelo.setFocusable(false);

        jTextFieldMotorista.setEditable(false);
        jTextFieldMotorista.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldMotorista.setFocusable(false);

        jLabel1.setText("KG");

        jLabel2.setText("M²");

        jTextFieldPeso.setEditable(false);
        jTextFieldPeso.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldPeso.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        jTextFieldPeso.setFocusable(false);

        jTextFieldCubagem.setEditable(false);
        jTextFieldCubagem.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldCubagem.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        jTextFieldCubagem.setFocusable(false);
        jTextFieldCubagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCubagemActionPerformed(evt);
            }
        });

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jCheckBoxAtivo.setText("Ativo");
        jCheckBoxAtivo.setEnabled(false);

        jButtonNovaBusca.setText("Nova Busca");
        jButtonNovaBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovaBuscaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelMotorista)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldMotorista))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelModelo)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldModelo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelFabricante)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelPlaca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelCubagem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldCubagem))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelPeso)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addComponent(jCheckBoxAtivo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonNovaBusca)))
                .addGap(36, 36, 36))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPlaca)
                    .addComponent(jTextFieldPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxAtivo)
                    .addComponent(jButtonBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFabricante)
                    .addComponent(jTextFieldFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelModelo)
                    .addComponent(jTextFieldModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMotorista)
                    .addComponent(jTextFieldMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPeso)
                    .addComponent(jTextFieldPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabelCubagem)
                    .addComponent(jTextFieldCubagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNovaBusca))
                .addGap(58, 58, 58))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonAltVeiculo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addComponent(jLabelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(276, 276, 276)
                        .addComponent(jLabelTitulo)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonVoltar)
                    .addComponent(jButtonAltVeiculo))
                .addGap(19, 19, 19))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
                    MenuVeiculo veiculo = new MenuVeiculo();
                    veiculo.setVisible(true);
                    dispose();                      
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jButtonAltVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAltVeiculoActionPerformed
        String Placa, Fabricante, Modelo, Motorista, Peso, Cubagem, ativo;
        if(jTextFieldPlaca.getText().equals("")){
            Placa = null;
        }else Placa =jTextFieldPlaca.getText();
        if(jTextFieldFabricante.getText().equals("")){
            Fabricante = null;
        }else Fabricante =jTextFieldFabricante.getText();
        if(jTextFieldModelo.getText().equals("")){
            Modelo = null;
        }else Modelo =jTextFieldModelo.getText();
        if(jTextFieldMotorista.getText().equals("")){
            Motorista = null;
        }else Motorista =jTextFieldMotorista.getText();
        if(jTextFieldPeso.getText().equals("")){
            Peso = null;
        }else Peso =jTextFieldPeso.getText();
        if(jTextFieldCubagem.getText().equals("")){
            Cubagem = null;
        }else Cubagem =jTextFieldCubagem.getText();
        
        if (jCheckBoxAtivo.isSelected()){
            ativo ="Y";
            } else ativo ="N";
        
        try {
            AlterarVeiculo.AtualizaVeiculo(Placa, Fabricante, Modelo, Motorista, Peso, Cubagem, ativo);
        } catch (SQLException ex) {
            Logger.getLogger(MenuVeiculoAlterar.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MenuVeiculoAlterar.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButtonAltVeiculoActionPerformed

    private void jTextFieldCubagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCubagemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCubagemActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        String ID="",Placa, Fabricante, Modelo, Motorista, Peso, Cubagem, Ativo;
        if(jTextFieldPlaca.getText().equals("")){
            Placa = null;
        }else Placa =jTextFieldPlaca.getText();
        try {
            ID = AlterarVeiculo.ValidaPlaca(Placa);
        } catch (ClassNotFoundException ex) {}
        if(!"B".equals(ID)){
            if(!"N".equals(ID)){
                if(!"false".equals(ID)){

                    jTextFieldFabricante.setEditable(true);
                    jTextFieldFabricante.setBackground(new java.awt.Color(255, 255, 255));
                    jTextFieldFabricante.setFocusable(true);

                    jTextFieldModelo.setEditable(true);
                    jTextFieldModelo.setBackground(new java.awt.Color(255, 255, 255));
                    jTextFieldModelo.setFocusable(true);

                    jTextFieldMotorista.setEditable(true);
                    jTextFieldMotorista.setBackground(new java.awt.Color(255, 255, 255));
                    jTextFieldMotorista.setFocusable(true);

                    jTextFieldPeso.setEditable(true);
                    jTextFieldPeso.setBackground(new java.awt.Color(255, 255, 255));
                    jTextFieldPeso.setFocusable(true);

                    jTextFieldCubagem.setEditable(true);
                    jTextFieldCubagem.setBackground(new java.awt.Color(255, 255, 255));
                    jTextFieldCubagem.setFocusable(true);

                    jTextFieldPlaca.setEditable(false);
                    jTextFieldPlaca.setBackground(new java.awt.Color(204, 204, 204));
                    jTextFieldPlaca.setFocusable(false);

                    jButtonAltVeiculo.setEnabled(true); 
                    jCheckBoxAtivo.setEnabled(true);
                    
                    try {
                        Fabricante = AlterarVeiculo.GetFabricante(ID);
                        Modelo = AlterarVeiculo.GetModelo(ID);
                        Motorista = AlterarVeiculo.GetMotorista(ID);
                        Peso = AlterarVeiculo.GetPeso(ID);
                        Cubagem = AlterarVeiculo.GetCubagem(ID);
                        Ativo = AlterarVeiculo.GetAtivo(ID);
                        
                        jTextFieldFabricante.setText(Fabricante);
                        jTextFieldModelo.setText(Modelo);
                        jTextFieldMotorista.setText(Motorista);
                        jTextFieldPeso.setText(Peso);
                        jTextFieldCubagem.setText(Cubagem);
                        
                        
                        if (Ativo.equals("Y")){
                        jCheckBoxAtivo.setSelected(true);
                        }
                        if (Ativo.equals("N")){
                        jCheckBoxAtivo.setSelected(false);
                        }
                        } catch (ClassNotFoundException ex) {
                            Logger.getLogger(MenuVeiculoAlterar.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    

                }else{
                    final JPanel panel = new JPanel();
                    JOptionPane.showMessageDialog(panel, "Placa não localizada, favor revisar", "ERRO!",
                    JOptionPane.WARNING_MESSAGE);
                }
            }else{
                final JPanel panel = new JPanel();
                JOptionPane.showMessageDialog(panel, "Placa Incorreta, favor revisar", "ERRO!",
                JOptionPane.WARNING_MESSAGE);
            }
        }else{
            final JPanel panel = new JPanel();
            JOptionPane.showMessageDialog(panel, "Preencher campo de Placa", "ERRO!",
            JOptionPane.WARNING_MESSAGE);
        }
           
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonNovaBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovaBuscaActionPerformed
            String A = null;        
            MenuVeiculoAlterar.AltVeiculo(A);            
            dispose();
    }//GEN-LAST:event_jButtonNovaBuscaActionPerformed

        

 
    /**
     * @param args the command line arguments
     */
    public static void AltVeiculo(String Placa) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuVeiculoAlterar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuVeiculoAlterar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuVeiculoAlterar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuVeiculoAlterar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuVeiculoAlterar(Placa).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAltVeiculo;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonNovaBusca;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JCheckBox jCheckBoxAtivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelCubagem;
    private javax.swing.JLabel jLabelFabricante;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelModelo;
    private javax.swing.JLabel jLabelMotorista;
    private javax.swing.JLabel jLabelPeso;
    private javax.swing.JLabel jLabelPlaca;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JFormattedTextField jTextFieldCubagem;
    private javax.swing.JTextField jTextFieldFabricante;
    private javax.swing.JTextField jTextFieldModelo;
    private javax.swing.JTextField jTextFieldMotorista;
    private javax.swing.JFormattedTextField jTextFieldPeso;
    private javax.swing.JTextField jTextFieldPlaca;
    // End of variables declaration//GEN-END:variables
}
